"""initial migration

Revision ID: 43d3a31d2560
Revises: d9305225907c
Create Date: 2017-04-23 22:10:22.843000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d3a31d2560'
down_revision = 'd9305225907c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('postname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'postname')
    # ### end Alembic commands ###
