"""initial migration

Revision ID: 49e6eb41ffd2
Revises: f96563d32f4f
Create Date: 2017-04-26 21:34:35.860000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e6eb41ffd2'
down_revision = 'f96563d32f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_avatar')
    # ### end Alembic commands ###
