"""initial migration

Revision ID: 6e1cd46a9893
Revises: 161f7c41de71
Create Date: 2017-12-10 20:11:32.275000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1cd46a9893'
down_revision = '161f7c41de71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('original', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('picture', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'picture')
    op.drop_column('posts', 'original')
    # ### end Alembic commands ###
