"""initial migration

Revision ID: b8d32b99edbb
Revises: ff15738dc99a
Create Date: 2017-04-22 14:04:16.899000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d32b99edbb'
down_revision = 'ff15738dc99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.drop_column('users', 'localtion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('localtion', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
