"""initial migration

Revision ID: f96563d32f4f
Revises: 43d3a31d2560
Create Date: 2017-04-24 20:58:51.322000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96563d32f4f'
down_revision = '43d3a31d2560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('readtimes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'readtimes')
    # ### end Alembic commands ###
